[package]
name = "rust_http_live_streaming"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
tokio = { version = "1.46.1", features = ["rt-multi-thread","full","fs"] }
tower-http = { version = "0.6", features = ["cors"] }
